logging:
  level: debug

dataStores:
  dataStore:
    mongo:
      uri: mongodb://localhost:27017
      timeout: 10
      databaseName: chux-cprs
      collectionName: ""
    redis:
      uri: redis://localhost:6379
      timeout: 10
      databaseName: ""
      collectionName: ""


