logging:
  level: debug

dataStores:
  dataStore:
    mongo:
      target: mongo
      uri: mongodb://localhost:27017
      timeout: 10
      databaseName: testdb
      collectionName: testcollection
